= Cassandra Cache Store
The Infinispan Community
:icons: font

== Introduction
Infinispan's `CassandraStore` leverages link:$$http://cassandra.apache.org/$$[Apache Cassandra's]
distributed database architecture to provide a virtually unlimited, horizontally
scalable persistent store for Infinispan's caches. 

== Configuration
In order to use this cache store you need to create an appropriate keyspace
on your Cassandra database, or configure the auto-create-keyspace to create it automatically.
The following CQL commands show how to configure the keyspace manually (using cqlsh for example):

.CQL
[source,sql]
----
CREATE KEYSPACE IF NOT EXISTS Infinispan WITH replication = {'class':'SimpleStrategy', 'replication_factor':1};
CREATE TABLE Infinispan.InfinispanEntries (key blob PRIMARY KEY, value blob, metadata blob);
----

You then need to add an appropriate cache declaration to your `infinispan.xml`
(or whichever file you use to configure Infinispan): 

.infinispan.xml
[source,xml]
----
<cache-container default-cache="cassandracache">
    <local-cache name="cassandracache">
        <persistence passivation="false">
            <cassandra-store xmlns="urn:infinispan:config:store:cassandra:8.2" auto-create-keyspace="true" keyspace="Infinispan" entry-table="InfinispanEntries" shared="true">
                <cassandra-server host="127.0.0.1" port="9042" />
                <connection-pool heartbeat-interval-seconds="30" idle-timeout-seconds="120" pool-timeout-millis="5" />
            </cassandra-store>
        </persistence>
    </local-cache>
</cache-container>
----

It is important the the shared property on the cassandra-store element is set to true
because all the Infinispan nodes will share the same Cassandra cluster.

== Limitations
The cache store uses Cassandras own expiration mechanisms (time to live = TTL) to handle expiration
of entries. Since TTL is specified in seconds, expiration lifespan and maxIdle values are handled
only with seconds-precision.

In addition to this, when both lifespan and maxIdle are used, entries in the cache store
effectively behave as if their lifespan = maxIdle, due to an existing bug https://issues.jboss.org/browse/ISPN-3202.
